### ISSUE TITLE
Summary of commands candidate for BLE calls

### ISSUE THREAD

**Issue by raphmur** [iainbullock/tesla_ble_mqtt_docker#15]
Thank you for all the additions @iainbullock 

I tried all of them to see which work. So far what I can tell:

**`product-info`** required Fleet API OAuth token --> **KO with BLE**

**`session-info`**: works. I got this first feedback message: 
```Usage: session-info PUBLIC_KEY DOMAIN
Retrieve session info for PUBLIC_KEY from DOMAIN
    PUBLIC_KEY: file containing public key (or corresponding private key)
    DOMAIN:     'vcsec' or 'infotainment'
```
Then called it with `session-info [path to public key] vcsec` and `session-info [path to public key] infotainment`. In both cases I got a json like answer with:

- counter: type integer, nothing fancy
- publicKey: type Hex. I assume some sort of handshake or directly the public key
- epoch
- clock time

So even though it works, nothing really useful

**`get`** required Fleet API OAuth token --> **KO with BLE**

**`post`** required Fleet API OAuth token --> **KO with BLE**

**`ping`**: works but not really sure what it does. Maybe equivalent to "force data update" in the previous Integration

**`remove-key`**: should work. You need to supply the `public.pem` public key file to remove it. Did not try further.

**`rename-key`** required Fleet API OAuth token --> **KO with BLE**

All the others should work

**Comment by raphmur** [comment]
Helper for other commands

**`seat-heater`**: requires seat position and power --> you may need to adapt your code

```
Usage: seat-heater SEAT LEVEL
Set seat heater at POSITION to LEVEL
    SEAT:  <front|2nd-row|3rd-row>-<left|center|right> (e.g., 2nd-row-left)
    LEVEL: off, low, medium, or high
```

**Comment by iainbullock** [comment]
That's useful thanks. I'm currently working on this in the dev branch. A few bugs on the version on github dev branch. I'll fix them later and release a new dev version

**Comment by iainbullock** [comment]
v1.0.21-dev has some HA Select entities for the front seat heaters. Please could you see if it works?

**Comment by raphmur** [comment]
I tried, it works.
However, A/C needs to be on otherwise you get this error:
`Failed to execute command: car could not execute command: cabin comfort remote settings not enabled
`

In addition calling **Auto Seat & Climate** gives the error below:
```
Invalid number of command line arguments: 1 (1 required, 1 optional).
Failed to execute command: invalid command line arguments
Usage: auto-seat-and-climate POSITIONS [ STATE ]
Turn on automatic seat heating and HVAC
    POSITIONS: 'L' (left), 'R' (right), or 'LR'
    STATE:     'on' (default) or 'off'
```

--> I suggest to force the command to `auto-seat-and-climate LR on`

**Comment by raphmur** [comment]
Note also that it is interesting that tesla-control gives a feedback on the A/C state...

**Comment by iainbullock** [comment]
The latest and probably final update has been released today in the main branch (v.1.1.2). It provides multi-car support (for commands, but not BLE presence), various bug fixes, and enhancements suggested by users.

The project is being migrated to a new one which has three developers (including me). With three of us working on it, we expect to improve functionality, quality, and responsiveness to issues. Check it out at https://github.com/tesla-local-control/tesla-local-control-addon

I will keep this project open until the first release at the new repository.

If your Issue remains unresolved by this release, please review existing Issues at the new repo, and open a new Issue there if required.

I will close the Issue here as the repo will soon be archived. 

Thanks a lot for your input and support on this project.
