### ISSUE TITLE
Summary of feedback message from tesla-control

### ISSUE THREAD

**Issue by raphmur** [iainbullock/tesla_ble_mqtt_docker#18]
I am logging all the messages brought by the tesla-control commands... This could be used to improve loop performance:

**charge-set-limit**:
- `Failed to execute command: car could not execute command: already_set` --> Detect the message and break the loop

**charging-start**:
- `Failed to execute command: car could not execute command: is_charging` --> Detect the message and break the loop

**Any command**:
- `Error: failed to find BLE beacon for [VIN] (SxxxxxxxxC): can't scan: context deadline exceeded****` --> Wait for `retry delay` and relaunch command. If `counter >=5`: log error "failed to send command to the car. Is the car awake and sufficiently close to bluetooth device?"
- `Error: context deadline exceeded` --> Same
- `Error: failed to find BLE beacon for XP7YGCELXPB053107 (Sdb4009e97649af12C): can't dial: can't dial: connection canceled` --> Same? Maybe increase the delay between commands

To be completed...

**Comment by epenet** [comment]
I would say that `Failed to execute command: car could not execute command: XXX` could be generic.
The car has rejected the command, there is no need to try again, regardless of XXX.

**Comment by raphmur** [comment]
Yes right Indeed
Though capturing the message to update an mqtt entity could be useful

**Comment by epenet** [comment]
Another one that doesn't need a retry:
```console
Attempt 1/5 to send command
Error loading credentials: could not load key: permission denied
tesla-control send command failed exit status 1. Retrying in 5
Attempt 2/5 to send command
Error loading credentials: could not load key: permission denied
...
```

**Comment by iainbullock** [comment]
The latest and probably final update has been released today in the main branch (v.1.1.2). It provides multi-car support (for commands, but not BLE presence), various bug fixes, and enhancements suggested by users.

The project is being migrated to a new one which has three developers (including me). With three of us working on it, we expect to improve functionality, quality, and responsiveness to issues. Check it out at https://github.com/tesla-local-control/tesla-local-control-addon

I will keep this project open until the first release at the new repository.

If your Issue remains unresolved by this release, please review existing Issues at the new repo, and open a new Issue there if required.

I will close the Issue here as the repo will soon be archived. 

Thanks a lot for your input and support on this project.

**Comment by raphmur** [comment]
This should solve this topic: https://github.com/tesla-local-control/tesla-local-control-addon/pull/40

**Comment by raphmur** [comment]
PR https://github.com/tesla-local-control/tesla-local-control-addon/pull/40 merged. Confirmed closed
